### PR TITLE
[BUGFIX] "New content-element" links to invalid URL

### PR DESCRIPTION
**Pull request by christian-fries**
Added bugfix https://review.typo3.org/#/c/41725/

### CODE REVIEW

**Comment by rfritzzz** [comment]
Hi Christian

I would like to try it in the backend. How can I reproduce the bug (and test the fix)?

**Comment by christian-fries** [comment]
Hi René,

to reproduce the bug:
Insert a gridelement on a page, then add a content element to that gridelement in page modul by clicking on the "+ Content" button. When you created the content element, you have another "+ Content" button below the newly created content element (with wrong styling). The link of that button is broken.

**Comment by rfritzzz** [comment]
Unfortunately I can't reproduce the bug. I followed your instructions closely, I think

**Comment by christian-fries** [comment]
With the latest version of your branch and a fresh install of Typo3 7.4 it works.

**Pull request closed without merging**
